config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  devise_for :users, controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  root 'items#index'


  resources :items do

    # collection => urlに/:idが表示されない。
    # member => urlに/:idが表示される。(三輪)
    member do
      get 'purchase'
      post 'purchase'
      post 'pay'
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      get 'list'
    end
  end

  resources :users, only: [:show] do
    member do
      get 'amount'
      get 'point'
    end
  end
  resources :sending_destinations, only: [:new, :create, :edit, :update]
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :sending_destinations
  has_many :items
  has_many :cards
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # userが買った商品のアソシエーション
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  # userが現在売っている商品のアソシエーション
  has_many :saling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  # userが既に売った商品のアソシエーション
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"

  validates :nickname,presence: true, length: {maximum: 8}
  validates :last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :birth_day, presence: true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_sending_destination_path(resource) 
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
  end

  
  def show
    @user = current_user
    @sending_destination = SendingDestination.where(user_id: current_user.id)

    # 現在出品中の商品
    @saling_items = @user.saling_items
    # 売却済みの商品
    @sold_items = @user.sold_items
    # 購入した商品
    @buyer_items = @user.buyed_items
  end  

  def amount
    @user = current_user
    @sold_items = @user.sold_items
  end


  def point
    @user = current_user
    @sold_items = @user.sold_items
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/amount.html.haml
.amount_container
  .amount_top_index
    %h2 #{@user.nickname}さんの売上金額

  .amount_price_content
    - amount_price = 0
    - @sold_items.each do |item|
      - amount_price = amount_price + item.price
    = icon("fas", "coins")
    %p #{amount_price}円

  .back_to_mypage
    = link_to "マイページへ戻る", user_path(@user)
 

app/views/users/point.html.haml
.amount_container
  .amount_top_index
    %h2 #{@user.nickname}さんのポイント

  .amount_price_content
    - amount_price = 0
    - point = 0
    - @sold_items.each do |item|
      - amount_price = amount_price + item.price
      - point = (amount_price * 0.1).round(0)
    = icon("fab", "pinterest-square")
    %p #{point}pt

  .back_to_mypage
    = link_to "マイページへ戻る", user_path(@user)
 

app/views/users/show.html.haml
.header_index
  = render partial: 'items/header_index' 
  
.user_content
  .user_content__info
    %h2
      =current_user.nickname
    %p 出品数 : #{@saling_items.length} /  購入数 : #{@buyer_items.length}

  .user_content__items
    %ul
      %list 
        = link_to '出品する',new_item_path
      %list 
        %a(class="exhibision-now") 出品した商品 - 出品中
        .exhibision-now-info
          - if @saling_items.length != 0
            - @saling_items.each do |item|
              .items
                .items-status 出品中
                = image_tag item.images.first.image_url.url
                = link_to "#{item.name}", item_path(item), class:"to_items_show" 
          - else
            .items
              %h3 出品中の商品はありません
      %list 
        %a(class="exhibision-end") 出品した商品 - 売却済み
        .exhibision-end-info
          - if @sold_items.length != 0
            - @sold_items.each do |item|
              .items
                .items-status 売却済
                = image_tag item.images.first.image_url.url
                = link_to "#{item.name}", item_path(item), class:"to_items_show" 
          - else
            .items
              %h3 売却済みの商品はありません
      %list 
        %a(class="purchase") 購入した商品 - 過去の取引
        .purchase-info
          - if @buyer_items.length != 0
            - @buyer_items.each do |item|
              .items
                .items-status 購入済
                = image_tag item.images.first.image_url.url
                = link_to "#{item.name}", item_path(item), class:"to_items_show" 
          - else
            .items
              %h3 購入した商品はありません
  .user_content__sales
    %p 売上情報
    %ul
      %list 
        = link_to '売上金額', amount_user_path(@user)
      %list 
        = link_to 'ポイント', point_user_path(@user)
  .user_content__config
    %p 設定
    %ul
      %list 
        = link_to '本人情報',edit_user_registration_path
      %list 
        = link_to '発送・お届け先住所',  edit_sending_destination_path(@sending_destination.ids)
      %list 
        = link_to 'カード情報',new_card_path
      %list 
        %a(class="log-out") ログアウト
        .log-out__btn
          = link_to "ログアウト",destroy_user_session_path , method: :delete

.footer_index
  = render partial: 'items/footer_index' 