config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  devise_for :users, controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  root 'items#index'


  resources :items do

    # collection => urlに/:idが表示されない。
    # member => urlに/:idが表示される。(三輪)
    member do
      get 'purchase'
      post 'purchase'
      post 'pay'
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      get 'list'
    end
  end

  resources :users, only: [:show] do
    member do
      get 'amount'
      get 'point'
    end
  end
  resources :sending_destinations, only: [:new, :create, :edit, :update]
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user, optional: true 
  has_many :comments
  belongs_to :category
  belongs_to :status
  belongs_to :postage_type
  belongs_to :prefecture
  belongs_to :need_day
  belongs_to :sending_destination, optional: true 
  has_many :images, dependent: :destroy

  # userとのアソシエーション
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true 

  validates :name, presence: true, length:{maximum: 40}
  validates :price, presence: true, numericality:{greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
  validates :introduction, presence: true, length:{maximum: 1000}

  # imagesテーブルへのバリデーション（画像の空の保存を許可しないバリデーション）（三輪）
  validates_associated :images
  validates :images, presence: true

  accepts_nested_attributes_for :images, allow_destroy: true  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  # @item = Item.find(params[:id])のbefore_action（三輪）

  before_action :set_item, except: [:index, :new, :create, :get_category_children, :get_category_grandchildren]

  before_action :check_user_signed_in, only: [:new, :create, :edit, :update, :destroy, :purchase]

  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  before_action :set_category_parent_array, only: [:create, :edit, :update]


  def index
    @items = Item.where(buyer_id: nil)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render new_item_path
    end
  end

  def new
    @item = Item.new
    @item.images.new
    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def show
    @user = User.find(@item.seller_id)
    @status = @item.status
    @postage_type = @item.postage_type
    @prefecture = @item.prefecture
    @need_day = @item.need_day
    @images = @item.images
    @grandchild = Category.find(@item.category_id)
    @child = @grandchild.parent
    @parent = @child.parent
  end  

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def purchase
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to new_card_path, notice: "クレジットカード情報を入力してください"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def pay
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
      amount: @item.price, #支払金額を入力
      customer: card.customer_id, #顧客ID
      currency: 'jpy', #日本円
    )
    @item.buyer_id = current_user.id
    @item.save
    redirect_to root_path, notice: "支払いが完了しました"
  end

  def list
    @items = Item.where(buyer_id: nil)
    @item = Item.find(params[:id])
    @images = @item.images
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def edit
    @images = @item.images
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to item_path
    end

  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :brand_name, :status_id, :postage_type_id, :prefecture_id, :need_day_id, :price, :category_id, images_attributes: [:image_url, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def ensure_correct_user
    @item = Item.find(params[:id])
    if @item.seller_id != current_user.id
      flash[:notice] = "権限がありません"
      redirect_to root_path
    end
  end

  private
  def check_user_signed_in
    if user_signed_in? == false
      flash[:notice] = "ログインしてください"
      redirect_to root_path
    end
  end

  def set_category_parent_array
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end  

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer_index.html.haml
.footer
  .footer__flex
    %ul.guide
      %li.about__FURIMA
        .furima FURIMAについて
        .content 会社概要（運営会社）
        .content プライバシー
        .content フリマ利用規約
        .content ポイントに関する特約
      %li.look__FURIMA
        .furima FURIMAを見る
        .content カテゴリー一覧
        .content ブランド一覧
      %li.guide__FURIMA
        .furima ヘルプ＆ガイド
        .content FURIMAガイド
        .content FURIMAロゴ 利用ガイドライン
        .content お知らせ
  .footer__logo
    = link_to "/" do
      = image_tag "logo/logo.png" , size: "180x55", class: 'logo'
    %p.copylight © FURIMA

app/views/items/_form.html.haml
.header_index
  = render partial: 'header_index' 

.main-logo
  = link_to "/" do
    = image_tag "logo/logo.png" , size: "180x60"

= form_for @item do |f|
  -# カテゴリーにもvalidationを掛けエラーメッセージが表示されるようにすること！（三輪）
  - if @item.errors
    %ul.error_message_items_new
      - @item.errors.full_messages.each do |message|
        %li.error_message_items_new__li= message

  .item-container
    .item-images
      .field
        .field__label
          %p 出品画像
          %span.field__label__require
            必須
        %p.image-info__message
          最大10枚までアップロードできます
        .field__input-images
          #input-images
            #previews
              - if @item.persisted?
                - @item.images.each_with_index do |image, i|
                  = image_tag image.image_url.url, data: { index: i }, width: "100", height: '100'

            = f.fields_for :images do |image|
              .js-file_group{"data-index" => "#{image.index}"}
                = image.file_field :image_url, class: 'js-file'
                %br/
                %span.js-remove 削除
              - if @item.persisted?
                = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
            - if @item.persisted?
              .js-file_group{"data-index" => "#{@item.images.count}"}
                = file_field_tag :image_url, name: "item[images_attributes][#{@item.images.count}][image_url]", class: 'js-file'
                .js-remove 削除

        .field__error-text
          %p.result-images 画像がありません
    .item-index
      .field
        .field__label
          %p 商品名
          %span.field__label__require
            必須
        .field__input--line
          = f.text_field :name, class:"item-name", placeholder: "40文字まで"
        .field__error-text
          %p.result-item-name 入力してください
      .field
        .field__label
          %p 商品の説明
          %span.field__label__require
            必須
        .field__input--text
          = f.text_area :introduction, class:"item-text",placeholder: "商品の説明（必須 1,000文字以内）"
        .counter
          %span.word-count 0
          %span / 1000
        .field__error-text
          %p.result-item-text 入力してください
    .item-info
      %h2 商品の詳細
      .field
        .field__label
        .listing-form-box
          .listing-product-detail__category
            = f.label 'カテゴリー', class: 'listing-default__label'
            %span.listing-default--require 必須
            .listing-select-wrapper
              .listing-select-wrapper__box
                = f.select :category, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
                %i.fas.fa-chevron-down.listing-select-wrapper__box--arrow-down  
        .field__error-text
          %p.result-category 選択してください
      .field
        .field__label
          %p ブランド
          %span.field__label__any
            任意
        .field__input--line
          = f.text_field :brand_name, class:"brand-name", placeholder: "例）シャネル"
        .field__error-text
      .field
        .field__label
          %p 商品の状態
          %span.field__label__require
            必須
        .field__select
          = f.collection_select :status_id, Status.all, :id, :status,{prompt: "選択して下さい"},{class: "field__select--status"}
        .field__error-text
          %p.result-status 選択してください
    .delivery-info
      %h2 配送について
      .field
        .field__label
          %p 配送料の負担
          %span.field__label__require
            必須
        .field__select
          = f.collection_select :postage_type_id, PostageType.all, :id, :postage_type,{prompt: "選択して下さい"},{class: "field__select--postage_type"}
        .field__error-text
          %p.result-postage 選択してください
      .field
        .field__label
          %p 発送元の地域
          %span.field__label__require
            必須
        .field__select
          = f.collection_select :prefecture_id, Prefecture.all, :id, :prefecture,{prompt: "選択して下さい"},{class: "field__select--prefecture"}
        .field__error-text
          %p.result-prefecture 選択してください
      .field
        .field__label
          %p 配送までの日数
          %span.field__label__require
            必須
        .field__select
          = f.collection_select :need_day_id, NeedDay.all, :id, :need_day,{prompt: "選択して下さい"},{class: "field__select--need_day"}
        .field__error-text
          %p.result-day 選択してください
    .pay-info
      %h2 価格（¥300〜9,999,999）
      .field
        .field__label
          %p 販売価格
          %span.field__label__require
            必須
        .field__input--price
          ¥
          = f.number_field :price, class:"input-price"
      .field__error-text
        %p.result-price 300以上9999999以下で入力してください
    .exhibition-button
      = f.submit "出品する", class:"exhibition-button__btn"
      = link_to "もどる", root_path, {class: "back-btn"}

      .footer_index
  = render partial: 'footer_index' 

app/views/items/_header_index.html.haml
.header 
  .header__inner
    .header__main
      .icon
        = link_to "/" do
          = image_tag "logo/logo.png" , size: "140x40"
      .search_box
        %input.input-text{name: "key", placeholder: "キーワードから探す", type: "search", value: "", class: "search"}/
        %button{type: "submit", class:'submit'} 
          .submit_icon
    .header__navigation
      %ul#category__brand
        %li.category
          = link_to "カテゴリー",'#', class: "category__btn"
          .menu_contents
            %ul
              %li
                = link_to "レディース",'#', class: "font"
              %li  
                = link_to "メンズ",'#', class: "font"
              %li  
                = link_to "ベビー•キッズ",'#', class: "font"
              %li  
                = link_to "インテリア•住まい•小物",'#', class: "font"  
              %li  
                = link_to "本•音楽•ゲーム",'#', class: "font"   
              %li  
                = link_to "おもちゃ•グッズ",'#', class: "font"   
              %li  
                = link_to "コスメ•香水•美容",'#', class: "font"   
              %li  
                = link_to "家電•カメラ",'#', class: "font"   
              %li  
                = link_to "スポーツ•レジャー",'#', class: "font"   
              %li  
                = link_to "ハンドメイド",'#', class: "font"   
              %li  
                = link_to "チケット",'#', class: "font"   
              %li  
                = link_to "自転車•オートバイ",'#', class: "font"   
              %li  
                = link_to "その他",'#', class: "font"   

        %li.brand
          = link_to "ブランド",'#', class: "brand__btn"
      - if user_signed_in?
        %ul.login__registration
          %li.username
            こんにちは
            =current_user.nickname
            さん
          %li.mypage
            = link_to "マイページ",user_path(current_user), class: "mypage__btn"
          %li.card
            = link_to "カード情報",card_path(current_user), class: "card__btn"
          %li.logout
            = link_to "ログアウト",destroy_user_session_path , method: :delete,class: "login__btn"
      - else
        %ul.login__registration
          
          %li.login
            = link_to "ログイン",new_user_session_path, class: "login__btn" 
          %li.restration
            = link_to "新規会員登録",new_user_registration_path, class: "registration__btn"

app/views/items/edit.html.haml
= render "form"

app/views/items/index.html.haml
.header_index
  = render partial: 'header_index' 
  
.contents
  .contents_top
    .contents_top_box
      .contents_top_box_contents
        .top_message
          人生を変えるフリマアプリ
        .top_sub_message
          FURIMAはだれでもかんたんに出品・購入できる
          %br
          フリマアプリです
        .link_contents
          = link_to image_tag('icon/appstore.jpg', class: "applestore"), 'https://www.apple.com/jp/ios/app-store/'
          = link_to image_tag('icon/googleplay.jpg', class: "googleplay"), 'https://play.google.com/'
          
          
  .contents__second
    
    %h1.contents_reason 
      FURIMAが選ばれる3つの理由
      .contents_second_title_after
    %ul.how_use
      %li.usage1
        .pic1
          = image_tag src="pict/pict-reason-01.jpg", size: "300x300"
          .picture1 1
        %p.display1 <b><span>3分</span>ですぐに出品</b>
        %p.display_comment1 スマホで入力するだけで簡単に出品<br>できる！</br>
        
      %li.usage2
        .pic2
          = image_tag src="pict/pict-reason-02.jpg", size: "300x300"
          .picture2 2
        %p.display2 <b><span>シンプル</span>で使いやすい</b>
        %p.display_comment2 めんどくさい入力は必要なく、<br>検索も購入もスムーズ！

      %li.usage3
        .pic3
          = image_tag src="pict/pict-reason-03.jpg", size: "300x300"
          .picture3 3
        %p.display3  <b>手数料<span>業界最安</span></b>
        %p.display_comment3 最大3%でお得に出品&購入！！

  .contents_third
    .contents_third_inner
      .contents_third_inner_title 会員数日本1位
      .contents_third_inner_sub_title
        <b>FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。</b>
      .contents_third_inner_icon
        = link_to image_tag('icon/appstore.jpg', class: "applestore"), 'https://www.apple.com/jp/ios/app-store/'
        = link_to image_tag('icon/googleplay.jpg', class: "googleplay"), 'https://play.google.com/'


  .contents_forth
    
    %h1.contents_feature FURIMAの特徴
    .contents_forth_title_after
    %ul.how_use
      %li.usage1
        .pic1
        = image_tag src="icon/icon-01.png", size: "300x300"
        %p.display 簡単に売り買いできる
        %p.display_comment スマホひとつで、いつでもどこでも<br>簡単に出品・購入が可能！
          
      %li.usage2
        .pic1
        = image_tag src="icon/icon-03.png", size: "300x300"
        %p.display 売上金は即日振込みに対応
        %p.display_comment 午前9時までに振込を依頼いただければ、<br>翌日に指定の口座に入金いたします!

      %li.usage3
        .pic1
        = image_tag src="icon/icon-04.png", size: "300x300"
        %p.display 様々な支払いに対応
        %p.display_comment お支払いは、クレジットカードだけでなく、<br>ポイントや売上金など多彩な方法があります。

  .contents_fifth
    .contents_pickup
      %h1.contents_feature 
      ピックアップカテゴリー
      - if user_signed_in?
        %h3.list_contents 
          = link_to "アーカイブ", list_item_path(current_user), class: "list_contents"
      - else
        %h3.list_contents 
          = link_to "アーカイブ", new_user_session_path, class: "list_contents"
      %ul.how_use
        - @items.each do |item|
          .usage1
            = link_to item_path(item), class: "usage" do
              .picture_top
                - item.images.first(1).each do |image|
                  = image_tag image.image_url.to_s, class: "picture__top--item"
              .picture__top--price 
                ¥
                = item.price
              .picture__bottom
                .picture__bottom--text
                  = item.name
    .contents_archive
      %h1.contents_feature 
      ピックアップブランド
      - if user_signed_in?
        %h3.list_contents 
          = link_to "出品商品一覧", list_item_path(current_user), class: "list_contents"
      - else
        %h3.list_contents 
          = link_to "出品商品一覧", new_user_session_path, class: "list_contents"
      %ul.how_use
        - @items.each do |item|
          .usage1
            = link_to item_path(item), class: "usage" do
              .picture_top
                - item.images.first(1).each do |image|
                  = image_tag image.image_url.to_s, class: "picture__top--item"
              .picture__top--price 
                ¥
                = item.price
              .picture__bottom
                .picture__bottom--text
                  = item.name



  .contents_sixth
    .sixth_inner
      .inner_title
        だれでもかんたん、人生を変えるフリマアプリ
      .inner_sub_title
        今すぐ無料ダウンロード！
      .inner_icon
        = link_to image_tag('icon/appstore.jpg', class: "applestore"), 'https://www.apple.com/jp/ios/app-store/'
        = link_to image_tag('icon/googleplay.jpg', class: "googleplay"), 'https://play.google.com/'


- if user_signed_in?
  .purchase_btn
    =link_to "/items/new" do
      .purchase_btn_text
        出品する
      .purchase_btn_icon
- else
  .purchase_btn
    =link_to "/users/sign_in" do
      .purchase_btn_text
        出品する
      .purchase_btn_icon


.footer_index
  = render partial: 'footer_index' 

app/views/items/list.html.haml
.header_index
  = render partial: 'header_index' 
  


.list_header
  .list_title
    出品商品一覧
  
.listing
  .list_items
    - @items.each do |item|
      .square
        = link_to item_path(item), class: "square1" do
          .picture_top
            - item.images.first(1).each do |image|
              = image_tag image.image_url.to_s, class: "picture__top--item"
          .picture__top--price
            ¥
            = item.price
          .picture__bottom
            %p.picture__bottom--text
              = item.name




.footer_index
  = render partial: 'footer_index' 

app/views/items/new.html.haml
= render "form"

app/views/items/purchase.html.haml
.header_index
  = render partial: 'items/header_index' 
  

.purchase-container
  .main-logo
    = link_to "/" do
      = image_tag(image_path('logo/logo.png'), class: 'logo')
  .purchase-item-container
    .top-content
      %h1 購入内容の確認
    .item
      .item__image
        = image_tag @item.images.first.image_url.to_s, class: "purchase-item-image"
      .item__info
        .item__info--name
          %p
            = @item.name
        .item__info--price
          %span.price_left 送料込み（税込）
          %span.price_right 
            ¥
            = number_to_currency(@item.price, :unit => "円")
            
    .item
      .price-text
        支払い金額
      .item-price
        ¥
        = number_to_currency(@item.price, :unit => "円")
    
    .item
      .card-text
        支払い方法
      .card-info
        - if @default_card_information.blank?
        - else
          -#以下カード情報を表示
          = "**** **** **** " + @default_card_information.last4
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year

    .purchase-button
      = form_tag(action: :pay, method: :post) do
        %button カードで支払う

.footer_index
  = render partial: 'items/footer_index' 







-# .header_index
-#   = render partial: 'items/header_index' 

-#   .purchase-item-container
-#     .top-content
-#       %h1 購入内容の確認
-#     .item
-#       .item__image
-#         =image_tag"mypage/food.png"
-#       .item__info
-#         .item__info--name
-#           %p 商品名がここに入ります
-#         .item__info--price
-#           %span.price_left 送料込み（税込）
-#           %span.price_right ¥5,000
-#     .item
-#       .price-text
-#         支払い金額
-#       .item-price
-#         ¥5,000

-#     .item
-#       .card-text
-#         支払い方法
-#       .card-info
-#         - if @default_card_information.blank?
-#         - else
-#           -#以下カード情報を表示
-#           = "**** **** **** " + @default_card_information.last4
-#           - exp_month = @default_card_information.exp_month.to_s
-#           - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
-#           = exp_month + " / " + exp_year
          
-#   .purchase-button
-#     = form_tag(action: :pay, method: :post) do
-#       -# .purchase-button__btn
-#       %button カードで支払う

-# .footer_index
-#   = render partial: 'items/footer_index' 

app/views/items/show.html.haml
//ログイン・新規登録ボタンの表示有無を後に確認、実装（近藤）
.header_index
  = render partial: 'items/header_index' 

.contentss
  .contentss__center
    .product__name
      %h1
        = @item.name
    %ul.image__detail
      %li.image
        #mainImage
          = image_tag src="#{@images[0].image_url}", size: "270x330"
        #imageList
          %ul.imageList__display
            - @images.each do |image|
              %li
              = image_tag src = "#{image.image_url}", size: "55x60"
      %li.detail
        %table
          %tr
            %td.exhibitor.left1
              出品者
              = @url
            %td.exhibitor__name.right1
              = @user.nickname
          %tr
            %td.left1
              カテゴリー
            %td.rightcategory
              = @parent.name
              %br
              = @child.name
              %br
              = @grandchild.name

          %tr
            %td.left1
              ブランド    
            %td.right1
              = @item.brand_name
          %tr
            %td.left2
              商品の状態    
            %td.right2
              = @status.status
          %tr
            %td.left2
              配送量の負担
            %td.sending__fee.right2
              = @postage_type.postage_type
          %tr
            %td.left2
              配送元地域
            %td.right2
              = @prefecture.prefecture
          %tr
            %td.left2
              配送日の目安
            %td.right2
              = @need_day.need_day  

    %ul.product__price
      %li.price
        ¥
        = number_to_currency(@item.price, :unit => "円")
      %li.tax
        （税抜き）
      %li.postage__type
        = @postage_type.postage_type
        
    - if current_user != @user
      .purchase__btn
        = link_to "購入画面に進む", "/items/#{params[:id]}/purchase", class: "purchase__btn__name"
    - else
      .edit__btn
        = link_to "商品の編集", "/items/#{params[:id]}/edit", class: "edit__btn__name"
      .destroy__btn
        = link_to "この商品を削除する" ,item_path(@item), method: :delete, class: "destroy__btn__name"

    .product__detail
      = safe_join(@item.introduction.split("\n"),tag(:br))

    .caution
      %p.caution__comment
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。

    .search_box
      %textarea.input__text
    .submit__btn      
      %button{type: "submit",  value: "送信する", class:'submit'}  
        .p
          コメントする
    
    .twitter_share
      この商品をシェアする
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button"%0a data-hashtags="FURIMA"%0a data-text="FURIMAアプリやで" %0a data-url=""%0a data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    
      .line-it-button{"data-color" => "default", "data-count" => "false", "data-lang" => "ja", "data-size" => "small", "data-type" => "share-a", "data-url" => "", "data-ver" => "3", :style => "display: none;"}
      %script{:async => "async", :defer => "defer", :src => "https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js"}


.footer_index
  = render partial: 'items/footer_index' 