config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  devise_for :users, controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  root 'items#index'


  resources :items do

    # collection => urlに/:idが表示されない。
    # member => urlに/:idが表示される。(三輪)
    member do
      get 'purchase'
      post 'purchase'
      post 'pay'
      get 'get_category_children', defaults: { fomat: 'json'}
      get 'get_category_grandchildren', defaults: { fomat: 'json'}
      get 'list'
    end
  end

  resources :users, only: [:show] do
    member do
      get 'amount'
      get 'point'
    end
  end
  resources :sending_destinations, only: [:new, :create, :edit, :update]
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"

  before_action :check_user_signed_in, only: [:new, :pay, :delete, :show]

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to new_card_path
    else
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to cards_path
      else
        redirect_to root_path, notice: "クレジットカード登録に失敗しました"
      end
    end
  end

  def delete
    card = Card.find_by(user_id: current_user.id)
    if card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to new_card_path
  end

  def show
    card = Card.find_by(user_id: current_user.id)
    if card.blank?
      redirect_to new_card_path
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  private
  def check_user_signed_in
    if user_signed_in? == false
      flash[:notice] = "ログインしてください"
      redirect_to root_path
    end
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
.header_index
  = render partial: 'items/header_index' 
  
.container
  .content__title
    %h2 クレジットカード情報入力
  .content__credit-card
    .content__credit-card__inner
      = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
        %label :カード番号
        %span 必須
        %br
        = text_field_tag "number", "", class: "input-numbe", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .image
          = image_tag(image_path('cards/visa.png'), class: 'visa')
          = image_tag(image_path('cards/master.png'), class: 'master')
          = image_tag(image_path('cards/jcb.png'), class: 'jcb')
          = image_tag(image_path('cards/amex.png'), class: 'amex')
          = image_tag(image_path('cards/diners.png'), class: 'diners')
          = image_tag(image_path('cards/discover.png'), class: 'discover')
        .cards-expire
          %label :有効期限
          %span 必須
          %br
          .cards-expire__wrap
            .cards-expire__wrap--half
              %select#exp_month{name: "exp_month", type: "text", class: 'input-expire'}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span.expire-text 月
              %br
            .cards-expire__wrap--half
              %select#exp_year{name: "exp_year", type: "text", class: "input-expire"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span.expire-text 年
        .cards-expire
          %label :セキュリティコード
          %span 必須
          = text_field_tag "cvc", "", class: "input-number", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        .content-bottom#card_token
          = submit_tag "登録する", class: 'content-bottom--add-btn', id: 'token_submit'
          
.footer_index
  = render partial: 'items/footer_index' 

app/views/cards/show.html.haml
.header_index
  = render partial: 'items/header_index' 
  

.card-show
  .card-title
    %h2 クレジットカード情報
  .content-card
    .card-infomation
      .info-left
        .info-left--name
          ご利用カード
        .info-left--number
          クレジットカード番号
        .info-left--date
          有効期限
      .info-right
        .info-right--name
          VISAカード
        .info-right--number
          = "**** **** **** " + @default_card_information.last4
        .info-right--date
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
      .btn
        = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button 削除する
    
.footer_index
  = render partial: 'items/footer_index' 